(function () {
  window.PlayrSiteNotices = [
    {
      id: 'site-notice-2026-04-27-homepage-game-grid-batching',
      title: 'Homepage game grid batching',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:45:00-04:00',
      summary: 'The homepage game library now loads in smaller batches with a Show more button so the first render stays lighter.',
      details: [
        'All Games, 1P Games, Multiplayer, and Competitive now start with a smaller first slice of game cards instead of painting the whole list immediately.',
        'Search and discovery filters still work across the full catalog, but extra cards now expand in chunks through the new Show more control.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-leaderboard-badge-icon-updates',
      title: 'Leaderboard badge icon updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:20:00-04:00',
      summary: 'Top-rank leaderboard badges now use the new custom icon set for 1st place, Top 3, Top 10, Top 25, Top 50, and Top 100.',
      details: [
        'The leaderboard badge chips now pull from the new PNG art set instead of using the old generated fallback icons.',
        'This update covers every local XP leaderboard tier from 1st place through Top 100.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-referral-icon-updates',
      title: 'Referral icon updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:05:00-04:00',
      summary: 'Referral badges now use the new custom icon set, with animation reserved for only the 10-referral and 25-referral tiers.',
      details: [
        'Recruiter I, Recruiter II, Recruiter III, Scoutmaster, and Signal Sovereign now pull from the new referral PNG icon set under the shared images folder.',
        'The 5-referral badge is now static, while the 10-referral and 25-referral badges keep the small animated treatment for extra emphasis.',
        'Referral reward text in settings was updated too so the descriptions match the live badge visuals.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-homepage-page-split',
      title: 'Homepage Load Lightening',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T13:30:00-04:00',
      summary: 'The heavyweight leaderboard and support surfaces now live on their own pages so the main PlayR homepage can stay lighter and respond faster.',
      details: [
        'The header leaderboard button now opens a dedicated rankings page instead of expanding the full leaderboard experience inside the homepage.',
        'Support Me now opens its own lightweight support page, which trims extra homepage sections and keeps the arcade focused on loading the game library first.',
        'The shared homepage script was also made page-aware so leaderboard-only UI no longer assumes the featured-game and game-grid widgets exist everywhere.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-gradient-direction-update',
      title: 'Gradient Direction Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T22:35:00-04:00',
      summary: 'Owner, VIP, and donation display-name gradients now run top-to-bottom instead of left-to-right for a cleaner stacked color look.',
      details: [
        'Styled names now fade vertically so high-rank identity treatments read more cleanly in compact chat rows and leaderboard cells.',
        'The update applies consistently to Owner, VIP, and every donation tier anywhere the shared identity renderer is used.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-tag-priority-gradient-update',
      title: 'Tag Priority & Gradient Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T21:10:00-04:00',
      summary: 'Identity tags now follow a stricter rank order around player names, and premium tags like Owner, VIP, and donation badges can tint names with gradients.',
      details: [
        'Owner and donation badges now sit before the display name, while VIP, leaderboard, referral, and level badges sort after it in one shared priority order.',
        'The settings tag picker now follows that same badge ranking so equipped tags stay in a consistent order across profiles, chats, and leaderboards.',
        'Owner, VIP, and donation tags can now apply gradient display-name styling, and the highest-ranked visible styled tag wins when multiple colored tags are equipped.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-icon-updates',
      title: 'Icon Updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T19:10:00-04:00',
      summary: 'The homepage leaderboard now opens to a cleaner Levels view by default, and account badges have been tightened into clearer icon-only chips with better hover popups.',
      details: [
        'The Leaderboard tab now scrolls directly into the leaderboard section, the new Levels board is the default view, and fake placeholder competitors no longer fill empty ranks.',
        'Leaderboard tables dropped the old Notes column, widened to use the available space better, and removed unsupported competitive boards like Sudoku, Simon Says, Typing Test, and Click Speed Test.',
        'Badge chips now keep only the icon visible for non-level tags, use an opaque styled tooltip on hover, allow up to 5 extra equipped badges, and use refreshed level icons for the new bracket ranges plus a dedicated level 999 mark.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-chopsticks-live',
      title: 'Chopsticks is live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T16:25:00-04:00',
      summary: 'PlayR now has a live 2-player Chopsticks room match with procedural hands, direct attack/transfer moves, room chat, and a 30-second move timer.',
      details: [
        'Chopsticks uses a first-person hand layout instead of a board, with your two hands in the foreground and the opponent across the table.',
        'The hand poses are rendered procedurally, so each hand visibly raises or hides fingers based on its current 0-4 count instead of relying on static number-only chips.',
        'Rounds are deterministic, illegal moves are blocked automatically, and timeout losses plus rematches feed into persistent per-room scoring.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-we-got-tags',
      title: 'We Got Tags!',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T14:40:00-04:00',
      summary: 'PlayR progression now fixes high-level XP rollovers, adds clearer level and status tags, and banks leaderboard XP until the daily reset instead of paying it out every session.',
      details: [
        'Level calculations now keep climbing correctly past the old cap edge, and level-up moments use a bigger cutscene with a dedicated You\'ve Leveled UP message.',
        'Accounts now unlock clearer small tag icons for level brackets, VIP, owner, referrals, leaderboard placement, and future donation support, with hover descriptions in settings and identity rows.',
        'Leaderboard bonus XP now gets banked through the day and pays out after the daily reset, which helps prevent session-spam abuse while keeping active-play XP immediate.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-created-connect-4',
      title: 'Created Connect-4',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T09:45:00-04:00',
      summary: 'Connect 4 now has a full multiplayer room flow with room codes, live chat, score tracking, animated coin drops, and round rematches instead of the older scaffold page.',
      details: [
        'Players can now create or join private Connect 4 rooms with c4- room codes and start live matches once both players are inside.',
        'The new board uses animated rail-based coin drops, winner highlighting, and a rematch reset animation that clears the board between rounds.',
        'Firestore rules now cover the Connect 4 room collection and chat messages so the new multiplayer flow follows the same authenticated room pattern as the other live games.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-ui-improvements',
      title: 'UI improvements',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T18:45:00-04:00',
      summary: 'Battleship now centers the boards more cleanly, hides room panels once you are inside, uses compact tooltip-based powers, and smooths out a few small command-deck UI details.',
      details: [
        'Battleship ship placement now stages positions before confirming them, uses longer placement and turn timers, and keeps your turn alive after a successful hit.',
        'Battleship powers now use compact cards with hover tooltips instead of inline descriptions, and each power restocks by 1 every 5 completed turns up to a max of 3.',
        'Battleship ship cards now keep the ship size beside the ship name in one cleaner line, and the leftover waiting-for-second-captain helper text has been removed.',
        'Battleship and Infinite Craft multiplayer now hide their create-or-join panels more consistently once a player is already in a room.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-battleship-ui-improvements-and-minor-bug-fixes',
      title: 'Battleship UI improvements and minor bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T18:05:00-04:00',
      summary: 'Battleship now wraps the boards with cleaner side panels, adds a dedicated powers deck, and fixes the host room panel so it closes properly after room creation.',
      details: [
        'The room summary and captain status now sit beside the boards instead of stacking above them, while the command deck and powers live in their own right-side panel.',
        'Radar, Airstrike, Mine, and Nuke now live in a dedicated powers panel with keyboard shortcuts for faster battle turns.',
        'The host create-or-join panel now hides consistently after creating a room, matching the multiplayer room flow used by Tic-Tac-Toe.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-favicon-update',
      title: 'Favicon Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T16:55:00-04:00',
      summary: 'PlayR pages now use the arcade logo as the browser tab icon instead of the default globe fallback.',
      details: [
        'The site now applies the PlayR Arcade logo as a shared favicon across pages.',
        'This keeps the browser tab icon aligned with the main brand instead of relying on the browser default.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-multiple-game-ui-updates-and-bug-fixes',
      title: 'Multiple Game UI Updates & Bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T16:30:00-04:00',
      summary: 'Battleship and Infinite Craft multiplayer now follow the site room-flow pattern more closely, with cleaner lobby transitions and consistent room-code behavior.',
      details: [
        'Battleship now opens on a centered lobby gate over blank boards, then switches into the full room UI only after a room is created or joined.',
        'The Battleship room summary now sits along the left side with the command deck below it, and the older combat feed panel has been removed.',
        'Infinite Craft multiplayer now auto-hides its room panel after joining and uses inf- room codes to match the current shared multiplayer naming pattern.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-battleship-neon-fleet',
      title: 'Battleship - Neon Fleet is live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T23:10:00-04:00',
      summary: 'Battleship now has a full Firebase room flow with timed turns, fleet placement, and a neon two-board command deck instead of the older scaffold page.',
      details: [
        'Players can create or join private Battleship rooms with bnf- codes and place fleets before battle begins.',
        'Matches now use live turn switching, timeout handling, combat logs, and a fog-of-war enemy tracking board.',
        'Firestore rules now cover the new Battleship room collection with the same authenticated room protections used by the other multiplayer games.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-infinite-craft-room-creation-bug',
      title: 'Infinite Craft Rooms Creation Bug Patched',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T21:45:00-04:00',
      summary: 'Firestore room rules now consistently validate multiplayer room prefixes so Infinite Craft rooms can be secured without drifting from the Tic-Tac-Toe setup.',
      details: [
        'Tic-Tac-Toe room documents now only allow IDs that begin with ttt-.',
        'Infinite Craft room documents now only allow IDs that begin with inf-.',
        'Messages and presence subcollections for both room types now follow the same authenticated access checks as their parent rooms.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-bug-fixes',
      title: 'Bug fixes to Tic Tac Toe UI',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T21:25:00-04:00',
      summary: 'Tic-Tac-Toe now keeps score badges aligned more cleanly and uses live account progression for the signed-in player in chat.',
      details: [
        'Score rows now keep player names, badges, and values on one aligned line instead of stretching the level chip into its own row.',
        'Placeholder labels like Waiting no longer inherit fake default level badges.',
        'Chat now refreshes the signed-in player badge from live progression data so the shown level stays in sync.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-improvement',
      title: 'Tic Tac Toe UI Improvement',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:55:00-04:00',
      summary: 'Tic-Tac-Toe chat author rows now line up more cleanly, especially when extra inline UI elements appear beside player names.',
      details: [
        'Chat author labels now use a tighter inline-flex layout.',
        'Name rows align more cleanly when badges or other inline markers are present.',
        'Wrapped author rows keep a more consistent visual rhythm.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-minor-bug-fixes',
      title: 'Minor bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:40:00-04:00',
      summary: 'Overscroll behavior and the homepage Easter egg were tuned so the gradient stays visible while the hidden message feels more tied to the extra pull gesture.',
      details: [
        'Root backgrounds still stay on the PlayR gradient during overscroll across the main site and game pages.',
        'Real overscroll is allowed again where the browser supports it instead of being fully suppressed.',
        'The homepage Easter egg now waits for an extra pull while already resting at the top, so it feels more like an overscroll secret than a normal site banner.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-xp-system-overhaul',
      title: 'XP progression has been rebalanced',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:10:00-04:00',
      summary: 'PlayR now uses a flatter level curve, session-based XP, softer anti-AFK scaling, and referral rewards that match the new progression plan.',
      details: [
        'Levels now follow the new fixed XP table instead of the older steep scaling curve.',
        'XP comes from active game sessions with time-based multipliers and Top 100 leaderboard bonuses applied at session end.',
        'Anti-AFK checks now scale penalties gradually and can pause XP after repeated suspicious behavior.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-overscroll-easter-egg',
      title: 'Overscroll flash cleaned up',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:45:00-04:00',
      summary: 'Overscroll now matches the site background instead of flashing white, and the homepage has a tiny top-edge Easter egg.',
      details: [
        'The root page background now matches the site gradient so overscroll feels consistent across pages.',
        'A subtle top-only Easter egg can appear on the homepage when someone keeps nudging past the upper scroll limit.',
        'The effect is throttled and non-blocking so it stays playful instead of distracting.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-home-url-and-updates-nav-fix',
      title: 'Homepage URL and updates header refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:20:00-04:00',
      summary: 'The homepage now stays on the clean root URL, the updates-page header pills match the shared style better, and the raw log link opens in a new tab.',
      details: [
        'The main brand link now returns to / without appending #home.',
        'Updates-page header buttons now keep the same chip styling as the rest of the site header.',
        'The raw changelog link now opens in a separate tab instead of replacing the updates page.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-clean-urls',
      title: 'Cleaner page URLs are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:00:00-04:00',
      summary: 'Information pages now use cleaner folder-based URLs, and the header pills on those pages now match the main site style.',
      details: [
        'About, Contact, Privacy, and Updates now open on clean routes like /about and /updates.',
        'Legacy .html links still forward to the new destinations so old bookmarks keep working.',
        'The information-page navigation pills now match the homepage button styling more closely.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-notification-popover-fix',
      title: 'Notification bell popover refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:35:00-04:00',
      summary: 'The bell now opens as a compact floating panel that no longer stretches the header, and it shows only the newest update.',
      details: [
        'The notification popover now floats independently so the header keeps its original size and shape.',
        'The bell now highlights only the latest public update instead of a stack of older notices.',
        'Clicking outside the panel closes it cleanly.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-update-process',
      title: 'Update tracking is now part of every release',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:20:00-04:00',
      summary: 'PlayR now pairs each user-facing release with a public update notice and changelog entry so maintenance stays visible.',
      details: [
        'User-visible releases now get a matching public notice in the site bell.',
        'The repo instructions now require update-log entries alongside real site changes.',
        'Public notices stay generic and never include private account or moderation details.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-2048-admin',
      title: '2048 owner tools and movement fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T22:43:09-04:00',
      summary: 'Added owner-only 2048 board tools and fixed a double-input issue that could make tiles jump unexpectedly.',
      details: [
        'Owner account can now add or remove custom 2048 tiles from an in-game admin panel.',
        'The main account settings modal now includes an owner-only XP adjustment panel.',
        'A duplicate keydown handling issue was fixed so one keypress no longer triggers two moves.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-site-trust-pages',
      title: 'Site policy and contact pages are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:20:33-04:00',
      summary: 'PlayR now has dedicated About, Contact, and Privacy pages linked across the site for easier trust and support access.',
      details: [
        'Added separate About, Contact, and Privacy pages.',
        'Added a footer and homepage legal/contact shortcuts so key information is easier to reach.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-vip-ad-free',
      title: 'VIP ad-free support is active',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:02:20-04:00',
      summary: 'The site now supports VIP ad suppression, which also powers account-based perk handling moving forward.',
      details: [
        'VIP accounts can browse without managed ads.',
        'The owner email is recognized as VIP automatically.',
        'This groundwork also supports future account perks and notice targeting.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-pacman-frogger-polish',
      title: 'Arcade polish update shipped',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T21:10:47-04:00',
      summary: 'Several games received quality updates, including Pac-Man, Frogger, Flappy Bird, Sudoku, and Infinite Craft room fixes.',
      details: [
        'Pac-Man now uses the updated maze and refined ghost behavior.',
        'Frogger, Flappy Bird, and Sudoku received gameplay and UI polish.',
        'Infinite Craft room creation was aligned with the allowed Firestore collection.',
      ],
    },
  ];
})();
