(function () {
  window.PlayrSiteNotices = [
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-bug-fixes',
      title: 'Bug fixes to Tic Tac Toe UI',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T21:25:00-04:00',
      summary: 'Tic-Tac-Toe now keeps score badges aligned more cleanly and uses live account progression for the signed-in player in chat.',
      details: [
        'Score rows now keep player names, badges, and values on one aligned line instead of stretching the level chip into its own row.',
        'Placeholder labels like Waiting no longer inherit fake default level badges.',
        'Chat now refreshes the signed-in player badge from live progression data so the shown level stays in sync.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-improvement',
      title: 'Tic Tac Toe UI Improvement',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:55:00-04:00',
      summary: 'Tic-Tac-Toe chat author rows now line up more cleanly, especially when extra inline UI elements appear beside player names.',
      details: [
        'Chat author labels now use a tighter inline-flex layout.',
        'Name rows align more cleanly when badges or other inline markers are present.',
        'Wrapped author rows keep a more consistent visual rhythm.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-minor-bug-fixes',
      title: 'Minor bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:40:00-04:00',
      summary: 'Overscroll behavior and the homepage Easter egg were tuned so the gradient stays visible while the hidden message feels more tied to the extra pull gesture.',
      details: [
        'Root backgrounds still stay on the PlayR gradient during overscroll across the main site and game pages.',
        'Real overscroll is allowed again where the browser supports it instead of being fully suppressed.',
        'The homepage Easter egg now waits for an extra pull while already resting at the top, so it feels more like an overscroll secret than a normal site banner.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-xp-system-overhaul',
      title: 'XP progression has been rebalanced',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:10:00-04:00',
      summary: 'PlayR now uses a flatter level curve, session-based XP, softer anti-AFK scaling, and referral rewards that match the new progression plan.',
      details: [
        'Levels now follow the new fixed XP table instead of the older steep scaling curve.',
        'XP comes from active game sessions with time-based multipliers and Top 100 leaderboard bonuses applied at session end.',
        'Anti-AFK checks now scale penalties gradually and can pause XP after repeated suspicious behavior.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-overscroll-easter-egg',
      title: 'Overscroll flash cleaned up',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:45:00-04:00',
      summary: 'Overscroll now matches the site background instead of flashing white, and the homepage has a tiny top-edge Easter egg.',
      details: [
        'The root page background now matches the site gradient so overscroll feels consistent across pages.',
        'A subtle top-only Easter egg can appear on the homepage when someone keeps nudging past the upper scroll limit.',
        'The effect is throttled and non-blocking so it stays playful instead of distracting.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-home-url-and-updates-nav-fix',
      title: 'Homepage URL and updates header refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:20:00-04:00',
      summary: 'The homepage now stays on the clean root URL, the updates-page header pills match the shared style better, and the raw log link opens in a new tab.',
      details: [
        'The main brand link now returns to / without appending #home.',
        'Updates-page header buttons now keep the same chip styling as the rest of the site header.',
        'The raw changelog link now opens in a separate tab instead of replacing the updates page.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-clean-urls',
      title: 'Cleaner page URLs are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:00:00-04:00',
      summary: 'Information pages now use cleaner folder-based URLs, and the header pills on those pages now match the main site style.',
      details: [
        'About, Contact, Privacy, and Updates now open on clean routes like /about and /updates.',
        'Legacy .html links still forward to the new destinations so old bookmarks keep working.',
        'The information-page navigation pills now match the homepage button styling more closely.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-notification-popover-fix',
      title: 'Notification bell popover refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:35:00-04:00',
      summary: 'The bell now opens as a compact floating panel that no longer stretches the header, and it shows only the newest update.',
      details: [
        'The notification popover now floats independently so the header keeps its original size and shape.',
        'The bell now highlights only the latest public update instead of a stack of older notices.',
        'Clicking outside the panel closes it cleanly.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-update-process',
      title: 'Update tracking is now part of every release',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:20:00-04:00',
      summary: 'PlayR now pairs each user-facing release with a public update notice and changelog entry so maintenance stays visible.',
      details: [
        'User-visible releases now get a matching public notice in the site bell.',
        'The repo instructions now require update-log entries alongside real site changes.',
        'Public notices stay generic and never include private account or moderation details.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-2048-admin',
      title: '2048 owner tools and movement fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T22:43:09-04:00',
      summary: 'Added owner-only 2048 board tools and fixed a double-input issue that could make tiles jump unexpectedly.',
      details: [
        'Owner account can now add or remove custom 2048 tiles from an in-game admin panel.',
        'The main account settings modal now includes an owner-only XP adjustment panel.',
        'A duplicate keydown handling issue was fixed so one keypress no longer triggers two moves.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-site-trust-pages',
      title: 'Site policy and contact pages are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:20:33-04:00',
      summary: 'PlayR now has dedicated About, Contact, and Privacy pages linked across the site for easier trust and support access.',
      details: [
        'Added separate About, Contact, and Privacy pages.',
        'Added a footer and homepage legal/contact shortcuts so key information is easier to reach.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-vip-ad-free',
      title: 'VIP ad-free support is active',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:02:20-04:00',
      summary: 'The site now supports VIP ad suppression, which also powers account-based perk handling moving forward.',
      details: [
        'VIP accounts can browse without managed ads.',
        'The owner email is recognized as VIP automatically.',
        'This groundwork also supports future account perks and notice targeting.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-pacman-frogger-polish',
      title: 'Arcade polish update shipped',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T21:10:47-04:00',
      summary: 'Several games received quality updates, including Pac-Man, Frogger, Flappy Bird, Sudoku, and Infinite Craft room fixes.',
      details: [
        'Pac-Man now uses the updated maze and refined ghost behavior.',
        'Frogger, Flappy Bird, and Sudoku received gameplay and UI polish.',
        'Infinite Craft room creation was aligned with the allowed Firestore collection.',
      ],
    },
  ];
})();
