(function () {
  window.PlayrSiteNotices = [
    {
      id: 'site-notice-2026-04-29-firestore-verified-shape-fix',
      title: 'Firestore profile sync fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T16:46:00-04:00',
      summary: 'Profile sync rules now accept the same verified-account shape the live app has been writing, which fixes another source of silent profile-update failures around banner changes and account saves.',
      details: [
        'The Firestore user-profile rules now allow boolean verified flags in addition to the newer map-based shape, so older accounts with verified set to false do not block later profile updates.',
        'That matters for banner saves and applies because those actions write through the same userProfiles document, so one invalid carried-forward field could reject the entire update even when the banner data itself was fine.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-custom-banner-save-apply-reliability-fix',
      title: 'Custom banner save/apply reliability fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T16:30:00-04:00',
      summary: 'Draw It and profile customization now use the lighter shared custom-banner library more consistently, which fixes several cases where banner saves or instant-apply actions could fail or burn extra save slots.',
      details: [
        'Gameplay-side profile writes now keep the heavy saved custom-banner list out of the main profile blob and rely on the dedicated shared banner library instead, which makes the banner flow less fragile.',
        'Saving the same banner art again now refreshes the existing saved entry instead of always consuming another slot, and owner@playr.io is now recognized as VIP inside Draw It before apply checks run.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-draw-it-save-and-profile-settings-polish',
      title: 'Draw It save flow and profile settings polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T23:58:00-04:00',
      summary: 'Draw It now places object actions and animation tools in cleaner spots, banner save/apply feedback is more visible, and profile customization now lives behind your own profile instead of the heavy main Settings view.',
      details: [
        'Group, ungroup, and delete actions now sit directly under the canvas, while selected-object animations move under the main scene settings for a tighter workspace layout.',
        'Saving or instantly applying a profile-banner scene from Draw It now shows stronger feedback, including visible loading state before export work starts and a direct apply-to-profile fallback button.',
        'Main Settings now points you to your own profile for badge and banner customization, and your self-profile uses a dedicated gear shortcut to open those profile settings faster.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-animated-banners-and-trolley-art-refresh',
      title: 'Animated banners and trolley art refresh',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T23:40:00-04:00',
      summary: 'Draw It custom banners can now store lightweight object animations, profile banners can play those scenes once on open, and the absurd trolley scene now uses the new custom sprite art.',
      details: [
        'Draw It now supports a compact selected-object animation panel, GIF-capable imports, finish-panel animated previews, and saved banner scene metadata so animated custom banners can be reused later without running heavy playback everywhere.',
        'Profile modals now have safer scrolling for longer staff moderation panels, and animated custom banners only play once when a profile is opened to keep the site responsive while still showing the motion work.',
        'The Absurd Trolley Problem scene now swaps the old placeholder trolley, lever, and victim art for the new custom trolley sprite sheets while keeping the existing decision flow and track movement logic intact.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-spend-bill-gates-overhaul',
      title: 'Spend Bill Gates’ Money overhaul',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T22:05:00-04:00',
      summary: 'The spending catalog now uses a much larger item list with caps, passive-return assets, risky payoff purchases, and a final receipt when the full $100B is spent.',
      details: [
        'New items were added across everyday goods, luxury buys, transport, property, and huge purchases, with max-purchase limits to keep the run readable and balanced.',
        'Some items now generate daily returns while a few major purchases can hit or flop, and finishing the run now opens a receipt showing what was bought to spend the full fortune.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-security-improvements',
      title: 'Security improvements',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T20:35:00-04:00',
      summary: 'Display-name filtering was tightened again, stale donation-tag conflicts were cleaned up, and heavy profile customization tools were moved out of the main Settings overlay.',
      details: [
        'The latest rules pass adds more blocked profanity coverage for account names, and the badge renderer now ignores old equipped donation entries that could stack with the automatic supporter badge.',
        'Profile banner and extra-tag customization now open from your own profile instead of loading inside the main Settings overlay, which lightens the Settings screen and reduces delayed scrolling.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-staff-role-ladder-and-rank-moderation',
      title: 'Staff role ladder and rank moderation update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T18:55:00-04:00',
      summary: 'Staff roles now use dedicated support, moderator, admin, owner, and VIP identity badges, and profile moderation tools now change based on rank and target state.',
      details: [
        'Support, moderator, and admin accounts now use their own permanent left-of-name staff icons and heavy role-based gradients, while VIP uses the new gold icon treatment and donation colors stay lighter to avoid staff impersonation.',
        'Profile moderation now respects rank limits, promotion cooldowns, and active mute/ban state, and staff copies can surface under a separate staff-notifications area in the notifications panel.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-custom-banner-shared-library-fix',
      title: 'Custom banner library fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T14:22:00-04:00',
      summary: 'Custom banners now use a dedicated shared banner library instead of relying only on the heavier profile cache blob, which makes them much more likely to appear in Settings after a Draw It save.',
      details: [
        'Draw It and Settings now read and write the same dedicated local custom-banner store, so saved banner options no longer depend on a full profile blob update succeeding first.',
        'The profile/theme export path also merges that shared banner library back into profile reads, so custom banner options can still appear in Settings even if the heavier profile cache lags behind.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-custom-banner-settings-sync-fix',
      title: 'Custom banners now stay in Settings',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T13:52:00-04:00',
      summary: 'Saved custom banners now persist more reliably in the Settings banner picker instead of disappearing after profile sync or cache merges.',
      details: [
        'The profile merge path now preserves newer local custom-banner entries instead of letting an older incoming snapshot replace the entire saved banner list.',
        'The Settings banner picker now prefers the freshest exported progression/profile state, so newly saved custom banners are more likely to appear as applyable options right away.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-hextris-side-lock-and-overlay-polish',
      title: 'Hextris side-lock and overlay polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T13:20:00-04:00',
      summary: 'Hextris blocks now lock onto the hex sides instead of the corners, the score sits in the middle of the core, and the start/restart flow now uses centered themed overlays.',
      details: [
        'The lane geometry was shifted so incoming pieces align with the six side faces of the hex core, which fixes the corner-landing look and makes the board read more clearly in motion.',
        'Hextris now opens with a centered start panel, shows a themed game-over restart panel with score and time, and also clears vertical same-colour stacks of three or more in addition to ring matches.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-hextris-launch',
      title: 'Hextris is live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T01:38:00-04:00',
      summary: 'Hextris now has a playable single-player survival mode with smooth falling blocks, fast eased hex rotation, quick-drop controls, and combo arc clears.',
      details: [
        'Use Left/Right or A/D to rotate the hex core, and hold Down or S to accelerate falling blocks while still keeping the rotation snap quick and smooth.',
        'The old scaffold page was replaced with a full playable build, and the noindex tag was removed from the Hextris page now that it is no longer an incomplete placeholder.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-profile-banner-state-and-join-date-fix',
      title: 'Profile banner state and join-date fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T01:05:00-04:00',
      summary: 'Profile banner changes now preserve newer local theme updates instead of getting overwritten by older profile snapshots, and join dates now use the account creation time more reliably.',
      details: [
        'Preset banner changes and saved custom banners now flow through the same merged profile-theme state, so older cache or cloud snapshots are less likely to stomp a newer banner choice.',
        'Profile join dates now preserve the earliest known account creation time from Firebase/local profile data instead of drifting to a later local cache creation date, and Draw It now hints that an already-open Settings panel may need a quick refresh after a new save.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-custom-banner-shared-save-path',
      title: 'Custom banner save path repair',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T00:32:00-04:00',
      summary: 'Draw It custom banners now save through the shared progression/profile layer that is actually loaded on game pages, so saved banners show up in Settings more reliably.',
      details: [
        'The custom-banner save action was moved into the shared progression/profile script used by game pages instead of depending on a hub-only account helper that Draw It did not load.',
        'Draw It now writes banners through that shared local profile store first and then performs its cloud sync attempt on top, so the Settings banner list can pick them up consistently on the same browser session.',
      ],
    },
    {
      id: 'site-notice-2026-04-29-dino-run-and-profile-layout-polish',
      title: 'Dino Run and profile layout polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-29T00:12:00-04:00',
      summary: 'Dino Run now ramps difficulty more fairly with cleaner pixel-art sprites and faster mid-air crouch drops, and profile tags/moderation controls fit the profile panel more reliably.',
      details: [
        'Dino Run now increases speed more gradually, spaces obstacles more safely, supports Shift as a crouch key, and lets mid-air crouching pull the dino down faster for tighter recoveries.',
        'The old chunky Dino Run art was replaced with cleaner pixel-style sprite rendering, while the profile modal now keeps tag tooltips wrapped inside the panel and lays out moderation buttons in a responsive grid so they stop clipping.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-custom-banner-cloud-save-fix',
      title: 'Custom banner save sync fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T23:55:00-04:00',
      summary: 'Custom banners now save through the shared account profile flow and push an immediate cloud sync so the Settings banner list can see them reliably.',
      details: [
        'Draw It now saves custom banners through the same shared profile-update path the main Settings screen already uses instead of relying on a parallel local-only flow.',
        'Profile-theme banner changes and new custom-banner saves now trigger an immediate Firestore sync, and saved banner art uses a lighter export format to make the cloud-backed save path more reliable.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-object-eraser-and-undo',
      title: 'Draw It object eraser and undo support',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T23:20:00-04:00',
      summary: 'Draw It now erases full objects instead of painting white over them, and Ctrl+Z can step back the latest edit.',
      details: [
        'The eraser now removes an entire touched object at once, so a completed brush line disappears as one object instead of leaving white paint over the canvas.',
        'Draw It now supports Ctrl+Z undo for recent edits, including strokes, object erases, movement, imports, grouping, and other scene changes.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-save-toast-and-unsaved-guard',
      title: 'Draw It save toast and unsaved-work tweak',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T22:05:00-04:00',
      summary: 'Saving a custom banner in Draw It now counts as saved work for the leave guard, and the confirmation message shows as a top-of-screen bubble instead of blending into the editor text.',
      details: [
        'Successful custom-banner saves now clear the local unsaved-work warning so players are not told their art is unsaved immediately after the banner was already stored.',
        'The save confirmation now appears as a more noticeable top-of-screen bubble, similar to the site easter-egg message style, to make the success state easier to spot.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-banner-save-and-layout-tune',
      title: 'Draw It banner-save and layout tune-up',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T21:45:00-04:00',
      summary: 'Draw It now places the canvas closer to the canvas-size controls, moves background controls into the selection area, and shows a save-in-progress notice while custom banners are being stored.',
      details: [
        'The main editor flow now places the canvas between the size picker and the tools so the left workspace no longer leaves a large dead gap above the whiteboard.',
        'Background controls were moved under the selection panel, and the extra gradient-only controls stay hidden unless Gradient is selected from the background dropdown.',
        'Saving a profile-banner design now shows a Loading... this wont take long popup while the banner is written, and the save path also re-imports the updated profile locally so custom banners show up in account data more reliably.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-wordle-ui-and-reveal-fix',
      title: 'Wordle layout and reveal polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T21:05:00-04:00',
      summary: 'Wordle Infinite now uses stronger PlayR-themed buttons, reveals submitted guesses one tile at a time, and fills the old empty side rail with help and colour guides.',
      details: [
        'The Wordle controls were restyled to better match the PlayR theme instead of relying on flatter default-looking blue buttons.',
        'Submitted guesses now animate tile-by-tile in sequence, and the old reveal glitch that could replay while typing a new guess was removed.',
        'The empty side space now includes a short how-to-play panel plus a colour legend so players can understand the board feedback at a glance.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-workspace-cleanup',
      title: 'Draw It workspace cleanup',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T20:35:00-04:00',
      summary: 'Draw It now uses a cleaner left-workspace and right-sidebar layout so the canvas stays prominent and the selection/import tools no longer leave big empty gaps.',
      details: [
        'The editor now stacks canvas-size, tools, canvas, and scene settings together in the main work column while stroke controls, imports, and selection tools live in a tighter sidebar.',
        'Selection controls were condensed into a smaller utility block with scale, group, ungroup, and delete actions instead of stretching into a tall mostly empty panel.',
        'Recent local drawings were moved out of the always-visible main page and into a collapsible section inside the finish/export modal to keep the drawing surface less cluttered.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-banner-save-polish',
      title: 'Draw It banner save polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T19:22:00-04:00',
      summary: 'Saving custom banners from Draw It now closes the finish panel on success and the modal close button matches the rest of the editor theme.',
      details: [
        'Successful custom-banner saves now dismiss the finish/export panel automatically and confirm with a simpler Saved to your banners message.',
        'The finish modal close button was restyled to match the PlayR chip-button look instead of falling back to an unthemed browser-style control.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-layout-and-gradient-pass',
      title: 'Draw It layout and gradient cleanup',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T19:05:00-04:00',
      summary: 'Draw It now puts the canvas first, trims down the visible controls, and uses a lighter gradient editor with draggable stops.',
      details: [
        'The Draw It workspace was rearranged into separate canvas-size, tools, canvas, settings, import, selection, and stroke-control panels so the whiteboard stays more central and easier to reach.',
        'Solid strokes now show just one colour picker, while gradient strokes open a cleaner editor with draggable stops plus an add-stop action instead of always showing extra colour controls.',
        'Hover help hints were added around the page to explain the main panels and actions without keeping long permanent instruction blocks on screen.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-social-panels-and-profile-tag-tuning',
      title: 'Friends tabs, profile fixes, and Draw It pixel mode',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T18:25:00-04:00',
      summary: 'The friends and profile panels were tightened up, Draw It gained a pixel drawing mode, and only owner or donation tags now stay beside display names.',
      details: [
        'The friends panel now opens on a Current Friends tab by default and separates current friends, incoming requests, and outgoing requests into dedicated tabs with faster accept, decline, cancel, and unfriend actions.',
        'Profiles now reserve beside-name tags for only owner and donation badges, while other equipped tags move into the profile panel itself, and the profile modal was adjusted to make opening profiles easier and keep owner moderation controls usable without clipping.',
        'Draw It now supports a pixel drawing mode alongside freehand strokes so players can build sharper blocky art styles as well as curved sketch lines.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-studio-upgrade',
      title: 'Draw It studio upgrade',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T16:50:00-04:00',
      summary: 'Draw It now behaves more like a full lightweight art studio with grouped editing, image imports, themed controls, and a centered export flow.',
      details: [
        'The Draw It editor now uses the shared PlayR button styling, moves the final preview into a centered finish panel, and supports solid or gradient strokes plus multi-stop gradient backgrounds.',
        'Players can now import PNG or JPEG images, scale and move them, select multiple objects, group or ungroup them, delete them together, and recolour selected strokes in one step.',
        'The editor also adds erasing, freeform canvas growth near the edges, recent local drawing snapshots, and profile-banner saves that still flow into the existing custom-banner account path.',
      ],
    },
    {
      id: 'site-notice-2026-04-28-draw-it-banners-and-profile-polish',
      title: 'Draw It, banner saves, and profile polish',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-28T12:30:00-04:00',
      summary: 'PlayR now has a new Draw It canvas game, stronger display-name filtering, slimmer owner moderation controls, and a tighter shared header layout.',
      details: [
        'Draw It adds four canvas modes: 16:9 wallpaper, 20:9 wallpaper, freeform expansion, and the site profile-banner size, with finished previews plus PNG/JPEG/WEBP downloads.',
        'Profile settings now support saved custom banner art, while applying those custom banners remains a VIP-only option with a live preview and referral-progress upsell toward the 25-referral VIP path.',
        'Owner moderation tools inside profiles now stay collapsed until Warn, Mute, or Ban is chosen, the shared header/leaderboard page navigation was tightened so the tabs stay on one line more reliably, and first-time signup can now be gated behind a server-verified captcha to cut down fake referrals.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-profile-friends-moderation',
      title: 'Profiles, friends, and moderation',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T19:20:00-04:00',
      summary: 'PlayR now has lazy-loaded user profiles, a dedicated friends panel, profile banners, favourite game tracking, and owner-driven account moderation tools.',
      details: [
        'Clicking a display name now opens a profile panel that shows join date, favourite game, total active time, XP leaderboard rank, public warning count, and the player banner.',
        'A new header friends button now opens incoming requests, outgoing requests, and current friendships, while profile panels can send or accept friend requests directly.',
        'The trusted owner account can now warn, mute, ban, unmute, and unban accounts from profile panels, with moderation state saved to the shared account profile document.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-xp-cloud-sync',
      title: 'XP cloud sync',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T17:10:00-04:00',
      summary: 'Signed-in account progression now syncs through Firestore so XP can follow the account across devices and feed the shared XP leaderboard.',
      details: [
        'PlayR now saves signed-in progression snapshots to the account profile document and rehydrates them when that account signs in again.',
        'The Levels leaderboard now refreshes from cloud-backed account profile data instead of only relying on the current browser cache.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-xp-hard-cap-safeguard',
      title: 'XP hard cap safeguard',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T16:05:00-04:00',
      summary: 'PlayR progression now enforces a hard maximum XP value so runaway account totals cannot cause site-wide lag.',
      details: [
        'The shared progression system now clamps all XP reads and writes to a fixed upper bound before level calculations run.',
        'Deferred leaderboard bonuses and session-end XP awards were updated too, so the safety cap applies everywhere the site can grant progression.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-homepage-game-grid-batching',
      title: 'Homepage game grid batching',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:45:00-04:00',
      summary: 'The homepage game library now loads in smaller batches with a Show more button so the first render stays lighter.',
      details: [
        'All Games, 1P Games, Multiplayer, and Competitive now start with a smaller first slice of game cards instead of painting the whole list immediately.',
        'Search and discovery filters still work across the full catalog, but extra cards now expand in chunks through the new Show more control.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-leaderboard-badge-icon-updates',
      title: 'Leaderboard badge icon updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:20:00-04:00',
      summary: 'Top-rank leaderboard badges now use the new custom icon set for 1st place, Top 3, Top 10, Top 25, Top 50, and Top 100.',
      details: [
        'The leaderboard badge chips now pull from the new PNG art set instead of using the old generated fallback icons.',
        'This update covers every local XP leaderboard tier from 1st place through Top 100.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-referral-icon-updates',
      title: 'Referral icon updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T15:05:00-04:00',
      summary: 'Referral badges now use the new custom icon set, with animation reserved for only the 10-referral and 25-referral tiers.',
      details: [
        'Recruiter I, Recruiter II, Recruiter III, Scoutmaster, and Signal Sovereign now pull from the new referral PNG icon set under the shared images folder.',
        'The 5-referral badge is now static, while the 10-referral and 25-referral badges keep the small animated treatment for extra emphasis.',
        'Referral reward text in settings was updated too so the descriptions match the live badge visuals.',
      ],
    },
    {
      id: 'site-notice-2026-04-27-homepage-page-split',
      title: 'Homepage Load Lightening',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-27T13:30:00-04:00',
      summary: 'The heavyweight leaderboard and support surfaces now live on their own pages so the main PlayR homepage can stay lighter and respond faster.',
      details: [
        'The header leaderboard button now opens a dedicated rankings page instead of expanding the full leaderboard experience inside the homepage.',
        'Support Me now opens its own lightweight support page, which trims extra homepage sections and keeps the arcade focused on loading the game library first.',
        'The shared homepage script was also made page-aware so leaderboard-only UI no longer assumes the featured-game and game-grid widgets exist everywhere.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-gradient-direction-update',
      title: 'Gradient Direction Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T22:35:00-04:00',
      summary: 'Owner, VIP, and donation display-name gradients now run top-to-bottom instead of left-to-right for a cleaner stacked color look.',
      details: [
        'Styled names now fade vertically so high-rank identity treatments read more cleanly in compact chat rows and leaderboard cells.',
        'The update applies consistently to Owner, VIP, and every donation tier anywhere the shared identity renderer is used.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-tag-priority-gradient-update',
      title: 'Tag Priority & Gradient Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T21:10:00-04:00',
      summary: 'Identity tags now follow a stricter rank order around player names, and premium tags like Owner, VIP, and donation badges can tint names with gradients.',
      details: [
        'Owner and donation badges now sit before the display name, while VIP, leaderboard, referral, and level badges sort after it in one shared priority order.',
        'The settings tag picker now follows that same badge ranking so equipped tags stay in a consistent order across profiles, chats, and leaderboards.',
        'Owner, VIP, and donation tags can now apply gradient display-name styling, and the highest-ranked visible styled tag wins when multiple colored tags are equipped.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-icon-updates',
      title: 'Icon Updates',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T19:10:00-04:00',
      summary: 'The homepage leaderboard now opens to a cleaner Levels view by default, and account badges have been tightened into clearer icon-only chips with better hover popups.',
      details: [
        'The Leaderboard tab now scrolls directly into the leaderboard section, the new Levels board is the default view, and fake placeholder competitors no longer fill empty ranks.',
        'Leaderboard tables dropped the old Notes column, widened to use the available space better, and removed unsupported competitive boards like Sudoku, Simon Says, Typing Test, and Click Speed Test.',
        'Badge chips now keep only the icon visible for non-level tags, use an opaque styled tooltip on hover, allow up to 5 extra equipped badges, and use refreshed level icons for the new bracket ranges plus a dedicated level 999 mark.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-chopsticks-live',
      title: 'Chopsticks is live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T16:25:00-04:00',
      summary: 'PlayR now has a live 2-player Chopsticks room match with procedural hands, direct attack/transfer moves, room chat, and a 30-second move timer.',
      details: [
        'Chopsticks uses a first-person hand layout instead of a board, with your two hands in the foreground and the opponent across the table.',
        'The hand poses are rendered procedurally, so each hand visibly raises or hides fingers based on its current 0-4 count instead of relying on static number-only chips.',
        'Rounds are deterministic, illegal moves are blocked automatically, and timeout losses plus rematches feed into persistent per-room scoring.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-we-got-tags',
      title: 'We Got Tags!',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T14:40:00-04:00',
      summary: 'PlayR progression now fixes high-level XP rollovers, adds clearer level and status tags, and banks leaderboard XP until the daily reset instead of paying it out every session.',
      details: [
        'Level calculations now keep climbing correctly past the old cap edge, and level-up moments use a bigger cutscene with a dedicated You\'ve Leveled UP message.',
        'Accounts now unlock clearer small tag icons for level brackets, VIP, owner, referrals, leaderboard placement, and future donation support, with hover descriptions in settings and identity rows.',
        'Leaderboard bonus XP now gets banked through the day and pays out after the daily reset, which helps prevent session-spam abuse while keeping active-play XP immediate.',
      ],
    },
    {
      id: 'site-notice-2026-04-26-created-connect-4',
      title: 'Created Connect-4',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-26T09:45:00-04:00',
      summary: 'Connect 4 now has a full multiplayer room flow with room codes, live chat, score tracking, animated coin drops, and round rematches instead of the older scaffold page.',
      details: [
        'Players can now create or join private Connect 4 rooms with c4- room codes and start live matches once both players are inside.',
        'The new board uses animated rail-based coin drops, winner highlighting, and a rematch reset animation that clears the board between rounds.',
        'Firestore rules now cover the Connect 4 room collection and chat messages so the new multiplayer flow follows the same authenticated room pattern as the other live games.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-ui-improvements',
      title: 'UI improvements',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T18:45:00-04:00',
      summary: 'Battleship now centers the boards more cleanly, hides room panels once you are inside, uses compact tooltip-based powers, and smooths out a few small command-deck UI details.',
      details: [
        'Battleship ship placement now stages positions before confirming them, uses longer placement and turn timers, and keeps your turn alive after a successful hit.',
        'Battleship powers now use compact cards with hover tooltips instead of inline descriptions, and each power restocks by 1 every 5 completed turns up to a max of 3.',
        'Battleship ship cards now keep the ship size beside the ship name in one cleaner line, and the leftover waiting-for-second-captain helper text has been removed.',
        'Battleship and Infinite Craft multiplayer now hide their create-or-join panels more consistently once a player is already in a room.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-battleship-ui-improvements-and-minor-bug-fixes',
      title: 'Battleship UI improvements and minor bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T18:05:00-04:00',
      summary: 'Battleship now wraps the boards with cleaner side panels, adds a dedicated powers deck, and fixes the host room panel so it closes properly after room creation.',
      details: [
        'The room summary and captain status now sit beside the boards instead of stacking above them, while the command deck and powers live in their own right-side panel.',
        'Radar, Airstrike, Mine, and Nuke now live in a dedicated powers panel with keyboard shortcuts for faster battle turns.',
        'The host create-or-join panel now hides consistently after creating a room, matching the multiplayer room flow used by Tic-Tac-Toe.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-favicon-update',
      title: 'Favicon Update',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T16:55:00-04:00',
      summary: 'PlayR pages now use the arcade logo as the browser tab icon instead of the default globe fallback.',
      details: [
        'The site now applies the PlayR Arcade logo as a shared favicon across pages.',
        'This keeps the browser tab icon aligned with the main brand instead of relying on the browser default.',
      ],
    },
    {
      id: 'site-notice-2026-04-25-multiple-game-ui-updates-and-bug-fixes',
      title: 'Multiple Game UI Updates & Bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-25T16:30:00-04:00',
      summary: 'Battleship and Infinite Craft multiplayer now follow the site room-flow pattern more closely, with cleaner lobby transitions and consistent room-code behavior.',
      details: [
        'Battleship now opens on a centered lobby gate over blank boards, then switches into the full room UI only after a room is created or joined.',
        'The Battleship room summary now sits along the left side with the command deck below it, and the older combat feed panel has been removed.',
        'Infinite Craft multiplayer now auto-hides its room panel after joining and uses inf- room codes to match the current shared multiplayer naming pattern.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-battleship-neon-fleet',
      title: 'Battleship - Neon Fleet is live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T23:10:00-04:00',
      summary: 'Battleship now has a full Firebase room flow with timed turns, fleet placement, and a neon two-board command deck instead of the older scaffold page.',
      details: [
        'Players can create or join private Battleship rooms with bnf- codes and place fleets before battle begins.',
        'Matches now use live turn switching, timeout handling, combat logs, and a fog-of-war enemy tracking board.',
        'Firestore rules now cover the new Battleship room collection with the same authenticated room protections used by the other multiplayer games.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-infinite-craft-room-creation-bug',
      title: 'Infinite Craft Rooms Creation Bug Patched',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T21:45:00-04:00',
      summary: 'Firestore room rules now consistently validate multiplayer room prefixes so Infinite Craft rooms can be secured without drifting from the Tic-Tac-Toe setup.',
      details: [
        'Tic-Tac-Toe room documents now only allow IDs that begin with ttt-.',
        'Infinite Craft room documents now only allow IDs that begin with inf-.',
        'Messages and presence subcollections for both room types now follow the same authenticated access checks as their parent rooms.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-bug-fixes',
      title: 'Bug fixes to Tic Tac Toe UI',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T21:25:00-04:00',
      summary: 'Tic-Tac-Toe now keeps score badges aligned more cleanly and uses live account progression for the signed-in player in chat.',
      details: [
        'Score rows now keep player names, badges, and values on one aligned line instead of stretching the level chip into its own row.',
        'Placeholder labels like Waiting no longer inherit fake default level badges.',
        'Chat now refreshes the signed-in player badge from live progression data so the shown level stays in sync.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-tic-tac-toe-ui-improvement',
      title: 'Tic Tac Toe UI Improvement',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:55:00-04:00',
      summary: 'Tic-Tac-Toe chat author rows now line up more cleanly, especially when extra inline UI elements appear beside player names.',
      details: [
        'Chat author labels now use a tighter inline-flex layout.',
        'Name rows align more cleanly when badges or other inline markers are present.',
        'Wrapped author rows keep a more consistent visual rhythm.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-minor-bug-fixes',
      title: 'Minor bug fixes',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:40:00-04:00',
      summary: 'Overscroll behavior and the homepage Easter egg were tuned so the gradient stays visible while the hidden message feels more tied to the extra pull gesture.',
      details: [
        'Root backgrounds still stay on the PlayR gradient during overscroll across the main site and game pages.',
        'Real overscroll is allowed again where the browser supports it instead of being fully suppressed.',
        'The homepage Easter egg now waits for an extra pull while already resting at the top, so it feels more like an overscroll secret than a normal site banner.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-xp-system-overhaul',
      title: 'XP progression has been rebalanced',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T20:10:00-04:00',
      summary: 'PlayR now uses a flatter level curve, session-based XP, softer anti-AFK scaling, and referral rewards that match the new progression plan.',
      details: [
        'Levels now follow the new fixed XP table instead of the older steep scaling curve.',
        'XP comes from active game sessions with time-based multipliers and Top 100 leaderboard bonuses applied at session end.',
        'Anti-AFK checks now scale penalties gradually and can pause XP after repeated suspicious behavior.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-overscroll-easter-egg',
      title: 'Overscroll flash cleaned up',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:45:00-04:00',
      summary: 'Overscroll now matches the site background instead of flashing white, and the homepage has a tiny top-edge Easter egg.',
      details: [
        'The root page background now matches the site gradient so overscroll feels consistent across pages.',
        'A subtle top-only Easter egg can appear on the homepage when someone keeps nudging past the upper scroll limit.',
        'The effect is throttled and non-blocking so it stays playful instead of distracting.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-home-url-and-updates-nav-fix',
      title: 'Homepage URL and updates header refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:20:00-04:00',
      summary: 'The homepage now stays on the clean root URL, the updates-page header pills match the shared style better, and the raw log link opens in a new tab.',
      details: [
        'The main brand link now returns to / without appending #home.',
        'Updates-page header buttons now keep the same chip styling as the rest of the site header.',
        'The raw changelog link now opens in a separate tab instead of replacing the updates page.',
      ],
    },
    {
      id: 'site-notice-2026-04-24-clean-urls',
      title: 'Cleaner page URLs are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-24T18:00:00-04:00',
      summary: 'Information pages now use cleaner folder-based URLs, and the header pills on those pages now match the main site style.',
      details: [
        'About, Contact, Privacy, and Updates now open on clean routes like /about and /updates.',
        'Legacy .html links still forward to the new destinations so old bookmarks keep working.',
        'The information-page navigation pills now match the homepage button styling more closely.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-notification-popover-fix',
      title: 'Notification bell popover refined',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:35:00-04:00',
      summary: 'The bell now opens as a compact floating panel that no longer stretches the header, and it shows only the newest update.',
      details: [
        'The notification popover now floats independently so the header keeps its original size and shape.',
        'The bell now highlights only the latest public update instead of a stack of older notices.',
        'Clicking outside the panel closes it cleanly.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-update-process',
      title: 'Update tracking is now part of every release',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T23:20:00-04:00',
      summary: 'PlayR now pairs each user-facing release with a public update notice and changelog entry so maintenance stays visible.',
      details: [
        'User-visible releases now get a matching public notice in the site bell.',
        'The repo instructions now require update-log entries alongside real site changes.',
        'Public notices stay generic and never include private account or moderation details.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-2048-admin',
      title: '2048 owner tools and movement fix',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T22:43:09-04:00',
      summary: 'Added owner-only 2048 board tools and fixed a double-input issue that could make tiles jump unexpectedly.',
      details: [
        'Owner account can now add or remove custom 2048 tiles from an in-game admin panel.',
        'The main account settings modal now includes an owner-only XP adjustment panel.',
        'A duplicate keydown handling issue was fixed so one keypress no longer triggers two moves.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-site-trust-pages',
      title: 'Site policy and contact pages are live',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:20:33-04:00',
      summary: 'PlayR now has dedicated About, Contact, and Privacy pages linked across the site for easier trust and support access.',
      details: [
        'Added separate About, Contact, and Privacy pages.',
        'Added a footer and homepage legal/contact shortcuts so key information is easier to reach.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-vip-ad-free',
      title: 'VIP ad-free support is active',
      category: 'system',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T20:02:20-04:00',
      summary: 'The site now supports VIP ad suppression, which also powers account-based perk handling moving forward.',
      details: [
        'VIP accounts can browse without managed ads.',
        'The owner email is recognized as VIP automatically.',
        'This groundwork also supports future account perks and notice targeting.',
      ],
    },
    {
      id: 'site-notice-2026-04-23-pacman-frogger-polish',
      title: 'Arcade polish update shipped',
      category: 'update',
      audience: 'public',
      severity: 'info',
      publishedAt: '2026-04-23T21:10:47-04:00',
      summary: 'Several games received quality updates, including Pac-Man, Frogger, Flappy Bird, Sudoku, and Infinite Craft room fixes.',
      details: [
        'Pac-Man now uses the updated maze and refined ghost behavior.',
        'Frogger, Flappy Bird, and Sudoku received gameplay and UI polish.',
        'Infinite Craft room creation was aligned with the allowed Firestore collection.',
      ],
    },
  ];
})();
